name: sasehacks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi
      - "uvicorn[standard]"
      - langchain-google-genai
      - langchain-deepseek
      - python-dotenv
      - scikit-learn
      - torch
      - transformers
      - pandas
      - numpy
      - keybert
      - dotenv
